# Generated by Django 3.0.3 on 2020-03-16 06:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fname', models.CharField(max_length=30)),
                ('lname', models.CharField(max_length=30)),
                ('email', models.EmailField(max_length=40, unique=True)),
                ('password', models.CharField(max_length=70)),
                ('dob', models.DateField()),
                ('gender', models.CharField(max_length=10)),
                ('description', models.CharField(blank=True, default='', max_length=160)),
                ('profession', models.CharField(blank=True, default='', max_length=30)),
                ('website', models.URLField(blank=True, default='')),
                ('image', models.ImageField(default='images/default.jpg', upload_to='images')),
            ],
        ),
        migrations.CreateModel(
            name='Post1',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField()),
                ('image', models.ImageField(default='', upload_to='photos')),
                ('video', models.FileField(default='', upload_to='videos')),
                ('cur_date', models.DateField()),
                ('uid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usermodule.User')),
            ],
        ),
        migrations.CreateModel(
            name='Friend',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.IntegerField()),
                ('fid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fid', to='usermodule.User')),
                ('uid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='uid', to='usermodule.User')),
            ],
        ),
    ]
