# Generated by Django 3.0.3 on 2020-03-18 06:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('usermodule', '0002_auto_20200316_2318'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.TextField()),
                ('postId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usermodule.Post1')),
                ('userId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usermodule.User')),
            ],
        ),
    ]
