# Generated by Django 3.0.3 on 2020-03-26 11:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('usermodule', '0003_comment'),
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('body', models.TextField()),
                ('msg_time', models.DateTimeField()),
                ('msg_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='msg_by', to='usermodule.User')),
                ('msg_to', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='msg_to', to='usermodule.User')),
            ],
        ),
    ]
