# Generated by Django 3.0.3 on 2020-03-26 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usermodule', '0004_message'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='ustatus',
            field=models.IntegerField(default=0),
        ),
    ]
